training:
    sample_frames: 128
    n_speakers_per_batch: 8
    n_utterances_per_speaker: 8
    n_prediction_steps: 12
    n_negatives: 17
    n_epochs: 22000
    scheduler:
        warmup_epochs: 150
        initial_lr: 1e-5
        max_lr: 4e-4
        gamma: 0.25
        milestones:
            - 20000
    checkpoint_interval: 500
    n_workers: 8
    log_interval: 10